"""change kelas to integer type

Revision ID: 885b376fa5e6
Revises: a3ae9671256f
Create Date: 2026-07-19 16:05:00.869237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885b376fa5e6'
down_revision: Union[str, Sequence[str], None] = 'a3ae9671256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account', 'kelas_nasabah',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('user', 'kelas',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'kelas',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('account', 'kelas_nasabah',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
